### ISSUE TITLE
Improve `Modal` styles

### ISSUE THREAD

**Issue by vitonsky** [vitonsky/react-elegant-ui#137]
Current implementation of `Modal` component is use CSS table to align center a content.
This solution is not allow to limit size of component by window size.

Instead this we should use flexbox. This solution leads to worsen support of ie11, but it's fine, because this browser is very old and we did not promised to support it.

Example styles:
```css
.Modal-Table {
	display: flex;
	justify-content: center;
	align-items: center;
	box-sizing: border-box;
	flex-wrap: wrap;
}

.Modal-Cell {
	max-width: 100%;
	padding: var(--modal-size-m-content-indent);
	box-sizing: border-box;
}

.Modal-Content {
	max-width: 100%;
	margin: 0;
}
```

Also, i suggest to improve naming semantic and rename `Table` and `Cell` components.
